export const FILTERS = [
  { id: 'normal', name: 'Normal', css: 'none', icon: '✨' },
  { id: 'bw', name: 'B&W', css: 'grayscale(100%)', icon: '🎞️' },
  { id: 'vintage', name: 'Vintage', css: 'sepia(60%) contrast(110%) brightness(90%)', icon: '📷' },
  { id: 'retro', name: 'Retro Film', css: 'sepia(40%) hue-rotate(-20deg) saturate(150%) contrast(105%)', icon: '🎬' },
  { id: 'glow', name: 'Soft Glow', css: 'brightness(115%) contrast(88%) saturate(110%)', icon: '🌸' },
  { id: 'warm', name: 'Warm', css: 'sepia(25%) saturate(130%) hue-rotate(5deg) brightness(105%)', icon: '🌅' },
  { id: 'cold', name: 'Cold', css: 'hue-rotate(195deg) saturate(70%) brightness(108%)', icon: '❄️' },
  { id: 'dreamy', name: 'Dreamy', css: 'brightness(112%) saturate(120%) contrast(90%)', icon: '☁️' },
  { id: 'kawaii', name: 'Kawaii', css: 'saturate(175%) brightness(112%) hue-rotate(325deg) contrast(95%)', icon: '🌷' },
  { id: 'cinematic', name: 'Cinematic', css: 'contrast(125%) brightness(82%) saturate(75%)', icon: '🎥' },
  { id: 'polaroid', name: 'Polaroid', css: 'contrast(108%) brightness(106%) saturate(88%) sepia(12%)', icon: '📸' },
  { id: 'sepia', name: 'Sepia', css: 'sepia(100%) contrast(105%)', icon: '🍂' },
];

export const STRIP_THEMES = [
  {
    id: 'minimal',
    name: 'Minimal',
    icon: '○',
    bg: '#FDFAF6',
    border: 'rgba(0,0,0,0.08)',
    textColor: '#1C1C1E',
    accentColor: '#C3B1E1',
    fontFamily: 'Inter',
    borderWidth: 6,
    borderRadius: 4,
    description: 'Clean & elegant',
  },
  {
    id: 'retro',
    name: 'Retro',
    icon: '◈',
    bg: '#F5E6C8',
    border: '#B8956A',
    textColor: '#4A3728',
    accentColor: '#B8956A',
    fontFamily: 'Space Mono',
    borderWidth: 8,
    borderRadius: 0,
    description: 'Old school vibes',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    icon: '◉',
    bg: '#EDE0D4',
    border: '#8B6914',
    textColor: '#3D2B1F',
    accentColor: '#C4922A',
    fontFamily: 'Playfair Display',
    borderWidth: 10,
    borderRadius: 2,
    description: 'Timeless classic',
  },
  {
    id: 'y2k',
    name: 'Y2K',
    icon: '★',
    bg: 'linear-gradient(135deg, #FFE4F0, #E4D0FF)',
    border: '#FF69B4',
    textColor: '#CC0066',
    accentColor: '#FF69B4',
    fontFamily: 'Inter',
    borderWidth: 6,
    borderRadius: 16,
    description: 'Early 2000s pop',
  },
  {
    id: 'kawaii',
    name: 'Kawaii',
    icon: '♡',
    bg: '#FFF0F5',
    border: '#FFB7C5',
    textColor: '#CC6680',
    accentColor: '#FFB7C5',
    fontFamily: 'Nunito',
    borderWidth: 8,
    borderRadius: 20,
    description: 'Cute & bubbly',
  },
  {
    id: 'dark',
    name: 'Noir',
    icon: '◆',
    bg: '#0E0E0F',
    border: '#333336',
    textColor: '#F2EDE8',
    accentColor: '#9B7FCC',
    fontFamily: 'Space Mono',
    borderWidth: 6,
    borderRadius: 4,
    description: 'Dark & moody',
  },
  {
    id: 'neon',
    name: 'Neon',
    icon: '⚡',
    bg: '#06060A',
    border: '#5EFFD8',
    textColor: '#5EFFD8',
    accentColor: '#FF54A4',
    fontFamily: 'Space Mono',
    borderWidth: 8,
    borderRadius: 4,
    description: 'Cyberpunk glow',
  },
  {
    id: 'wedding',
    name: 'Wedding',
    icon: '◎',
    bg: '#FFF9F5',
    border: '#D4AF8C',
    textColor: '#5C3D2E',
    accentColor: '#D4AF8C',
    fontFamily: 'Playfair Display',
    borderWidth: 12,
    borderRadius: 0,
    description: 'Elegant & romantic',
  },
  {
    id: 'birthday',
    name: 'Birthday',
    icon: '✦',
    bg: '#FFF4E6',
    border: '#FFB347',
    textColor: '#8B4513',
    accentColor: '#FFB347',
    fontFamily: 'Nunito',
    borderWidth: 8,
    borderRadius: 12,
    description: 'Festive & fun',
  },
  {
    id: 'film',
    name: 'Film Strip',
    icon: '▣',
    bg: '#1A1A1A',
    border: '#F5F5F0',
    textColor: '#F5F5F0',
    accentColor: '#FFD700',
    fontFamily: 'Space Mono',
    borderWidth: 10,
    borderRadius: 0,
    description: 'Cinematic reel',
  },
];

export const STICKERS = [
  // Hearts
  { id: 's1', emoji: '❤️', category: 'hearts' },
  { id: 's2', emoji: '🩷', category: 'hearts' },
  { id: 's3', emoji: '💜', category: 'hearts' },
  { id: 's4', emoji: '💙', category: 'hearts' },
  { id: 's5', emoji: '🤍', category: 'hearts' },
  { id: 's6', emoji: '💕', category: 'hearts' },
  // Stars
  { id: 's7', emoji: '⭐', category: 'stars' },
  { id: 's8', emoji: '✨', category: 'stars' },
  { id: 's9', emoji: '🌟', category: 'stars' },
  { id: 's10', emoji: '💫', category: 'stars' },
  { id: 's11', emoji: '🌙', category: 'stars' },
  // Flowers
  { id: 's12', emoji: '🌸', category: 'flowers' },
  { id: 's13', emoji: '🌷', category: 'flowers' },
  { id: 's14', emoji: '🌻', category: 'flowers' },
  { id: 's15', emoji: '🌹', category: 'flowers' },
  { id: 's16', emoji: '🌼', category: 'flowers' },
  // Fun
  { id: 's17', emoji: '🎀', category: 'fun' },
  { id: 's18', emoji: '🎉', category: 'fun' },
  { id: 's19', emoji: '🎊', category: 'fun' },
  { id: 's20', emoji: '🦋', category: 'fun' },
  { id: 's21', emoji: '🍓', category: 'fun' },
  { id: 's22', emoji: '🌈', category: 'fun' },
  // Face
  { id: 's23', emoji: '😊', category: 'face' },
  { id: 's24', emoji: '🥰', category: 'face' },
  { id: 's25', emoji: '😎', category: 'face' },
  { id: 's26', emoji: '🤩', category: 'face' },
  { id: 's27', emoji: '😈', category: 'face' },
  // Aesthetic
  { id: 's28', emoji: '🫧', category: 'aesthetic' },
  { id: 's29', emoji: '🍵', category: 'aesthetic' },
  { id: 's30', emoji: '📷', category: 'aesthetic' },
  { id: 's31', emoji: '🎞️', category: 'aesthetic' },
  { id: 's32', emoji: '🪩', category: 'aesthetic' },
  { id: 's33', emoji: '🌊', category: 'aesthetic' },
  { id: 's34', emoji: '🕯️', category: 'aesthetic' },
  { id: 's35', emoji: '🫀', category: 'aesthetic' },
];

export const STICKER_CATEGORIES = ['hearts', 'stars', 'flowers', 'fun', 'face', 'aesthetic'];

export const LAYOUTS = [
  { id: 'vertical', name: 'Classic Strip', icon: '▌', description: '1 × N vertical strip' },
  { id: 'grid', name: 'Grid', icon: '▦', description: '2-column grid layout' },
  { id: 'polaroid', name: 'Polaroid', icon: '◧', description: 'Polaroid-style cards' },
  { id: 'filmstrip', name: 'Film Strip', icon: '▬', description: 'Cinematic film reel' },
];

export const PHOTO_COUNTS = [
  { count: 3, label: '3 Photos', layout: 'classic', desc: 'Quick & sweet' },
  { count: 4, label: '4 Photos', layout: 'standard', desc: 'Perfect strip' },
  { count: 6, label: '6 Photos', layout: 'full', desc: 'More memories' },
];

export const BOOTH_FRAMES = [
  { id: 'none', name: 'No Frame', icon: '○' },
  { id: 'floral', name: 'Floral', icon: '🌸' },
  { id: 'retro', name: 'Retro Arch', icon: '◗' },
  { id: 'neon', name: 'Neon', icon: '⚡' },
  { id: 'stars', name: 'Stars', icon: '✨' },
  { id: 'minimal', name: 'Minimal', icon: '□' },
];

export { VIRTUAL_BACKGROUNDS, MUSIC_TRACKS } from './backgrounds.js';
